### ISSUE TITLE
Sonoff Zigbee Smart Water Valve: Incorrect `on_time` Duration (Payload Seconds Do Not Match Valve Response)

### ISSUE THREAD

**Issue by TapioJarnfors** [OmarAfet/structure-generator#2]
### Description

When using a Sonoff Zigbee Smart Water Valve (see: https://www.zigbee2mqtt.io/devices/SWV.html#sonoff-swv) with Zigbee2MQTT, sending a payload with the `on_time` key does not result in the expected valve open duration. For example, sending `on_time: 11` opens the valve for 110 seconds, and sending `on_time: 13` results in an unexpected duration with an odd value reported back.

#### Device Information

- **Device Type:** EndDevice
- **Zigbee Model:** SWV
- **Zigbee Manufacturer:** SONOFF
- **Description:** Zigbee smart water valve
- **Support status:** Supported
- **IEEE Address:** 0x7cc6b6fffe0d0509
- **Network address:** 0xC348 / 49992
- **Firmware build date:** 20240820
- **Firmware version:** 1.0.4
- **Manufacturer:** SONOFF
- **Model:** SWV
- **Power:** Battery 100%
- **Interview state:** Successful

#### Test Cases

**Case 1: 11 Seconds**

Home Assistant Button:
```yaml
- name: "Open Water Valve for testing 11seconds"
  unique_id: "open_water_valve_testing_11"
  command_topic: "zigbee2mqtt/sonoff_smart_water_valve1/set"
  payload_press: '{"state": "ON", "on_time": 11}'
  icon: mdi:water-pump
```

Zigbee2MQTT Log & Valve Status:
```json
{
  "cyclic_timed_irrigation": {
    "current_count": 1,
    "irrigation_duration": 110,
    "irrigation_interval": 0,
    "total_number": 1
  },
  ...
}
```

**Case 2: 13 Seconds**

Home Assistant Button:
```yaml
- name: "Open Water Valve for testing 13seconds"
  unique_id: "open_water_valve_testing_13"
  command_topic: "zigbee2mqtt/sonoff_smart_water_valve1/set"
  payload_press: '{"state": "ON", "on_time": 13}'
  icon: mdi:water-pump
```

Zigbee2MQTT Log & Valve Status:
```json
{
  "cyclic_timed_irrigation": {
    "current_count": 1,
    "irrigation_duration": 239,
    "irrigation_interval": -1078132736,
    "total_number": 1
  },
  ...
}
```

#### Expected Behavior

- Setting `on_time` to N should keep the valve ON for N seconds.

#### Actual Behavior

- The value reported back (and the actual valve operation) does not match the payload's `on_time` value.

#### Steps to Reproduce

1. Send an MQTT payload with `{ "state": "ON", "on_time": <N> }` to the topic `zigbee2mqtt/sonoff_smart_water_valve1/set` (via Home Assistant or MQTT Explorer).
2. Observe Zigbee2MQTT logs and the status reported by the valve.
3. Note the mismatch between sent `on_time` and reported/actual operation duration.

#### Relevant Hardware/Software
- Device: Sonoff Smart Water Valve (SWV)
- Home Assistant & MQTT Explorer (version: 0.4.0-beta.6)
- Zigbee2MQTT version: 2.3.0-1 ([Changelog](https://www.zigbee2mqtt.io/information/changelog.html))

#### Additional Information
- [Device reference](https://www.zigbee2mqtt.io/devices/SWV.html#sonoff-swv)
- Example logs and payloads included above.

---

If you need additional information, please be in contact.
